// <auto-generated />
using MedicalClinic.Data.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MedicalClinic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180609095606_MedicalClinic")]
    partial class MedicalClinic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MedicalClinic.Models.AdminModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("MedicalClinic.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("MedicalClinic.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PIN");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNum");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<int>("ResidenceId");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Sex");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ResidenceId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("MedicalClinic.Models.AppointmentModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DateOfApp");

                    b.Property<string>("DoctorId");

                    b.Property<string>("Hour");

                    b.Property<int>("IsConfirmed");

                    b.Property<string>("Notes");

                    b.Property<string>("PatientCardId");

                    b.Property<string>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientCardId");

                    b.HasIndex("RecipeId")
                        .IsUnique()
                        .HasFilter("[RecipeId] IS NOT NULL");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("MedicalClinic.Models.ClerkModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Receptionist");
                });

            modelBuilder.Entity("MedicalClinic.Models.DiagnosisModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppointmentId");

                    b.Property<string>("DeseaseName");

                    b.Property<string>("Symptoms");

                    b.Property<string>("Synopsis");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("MedicalClinic.Models.DoctorModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Specialization")
                        .IsRequired();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("MedicalClinic.Models.ExaminationModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NameOfExamination");

                    b.HasKey("Id");

                    b.ToTable("Examination");
                });

            modelBuilder.Entity("MedicalClinic.Models.GradeModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppointmentId");

                    b.Property<string>("Comment");

                    b.Property<int>("Grade");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("MedicalClinic.Models.MedicineModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("MedicalClinic.Models.PatientCardModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClerkId");

                    b.Property<string>("Date");

                    b.Property<string>("PatientId");

                    b.HasKey("Id");

                    b.HasIndex("ClerkId");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasFilter("[PatientId] IS NOT NULL");

                    b.ToTable("PatientCard");
                });

            modelBuilder.Entity("MedicalClinic.Models.PatientModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("MedicalClinic.Models.RecipeModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descrpition");

                    b.Property<string>("ExpDate");

                    b.HasKey("Id");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("MedicalClinic.Models.ReferralModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppointmentId");

                    b.Property<string>("DateOfIssuance");

                    b.Property<string>("ExaminationId");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ExaminationId")
                        .IsUnique()
                        .HasFilter("[ExaminationId] IS NOT NULL");

                    b.ToTable("Referral");
                });

            modelBuilder.Entity("MedicalClinic.Models.ResidenceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BuildingNum");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("FlatNum");

                    b.Property<string>("PostalCode");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("Residence");
                });

            modelBuilder.Entity("MedicalClinic.Models.WorkHoursModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DayofWeek");

                    b.Property<string>("DoctorId");

                    b.Property<string>("EndHour");

                    b.Property<string>("StartHour");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("WorkHours");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MedicalClinic.Models.AdminModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Admin")
                        .HasForeignKey("MedicalClinic.Models.AdminModel", "UserId");
                });

            modelBuilder.Entity("MedicalClinic.Models.ApplicationUser", b =>
                {
                    b.HasOne("MedicalClinic.Models.ResidenceModel", "residenceModel")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MedicalClinic.Models.AppointmentModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.DoctorModel", "DoctorModel")
                        .WithMany("AppointmentModel")
                        .HasForeignKey("DoctorId");

                    b.HasOne("MedicalClinic.Models.PatientCardModel", "PatientCardModel")
                        .WithMany("AppointmentModel")
                        .HasForeignKey("PatientCardId");

                    b.HasOne("MedicalClinic.Models.RecipeModel", "RecipeModel")
                        .WithOne("AppointmentModel")
                        .HasForeignKey("MedicalClinic.Models.AppointmentModel", "RecipeId");
                });

            modelBuilder.Entity("MedicalClinic.Models.ClerkModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Clerk")
                        .HasForeignKey("MedicalClinic.Models.ClerkModel", "UserId");
                });

            modelBuilder.Entity("MedicalClinic.Models.DiagnosisModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.AppointmentModel", "AppointmentModel")
                        .WithOne("DiagnosisModel")
                        .HasForeignKey("MedicalClinic.Models.DiagnosisModel", "AppointmentId");
                });

            modelBuilder.Entity("MedicalClinic.Models.DoctorModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Doctor")
                        .HasForeignKey("MedicalClinic.Models.DoctorModel", "UserId");
                });

            modelBuilder.Entity("MedicalClinic.Models.GradeModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.AppointmentModel", "AppointmentModel")
                        .WithOne("GradeModel")
                        .HasForeignKey("MedicalClinic.Models.GradeModel", "AppointmentId");
                });

            modelBuilder.Entity("MedicalClinic.Models.MedicineModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.RecipeModel", "RecipeModel")
                        .WithMany("MedicineModel")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("MedicalClinic.Models.PatientCardModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.ClerkModel", "ClerkModel")
                        .WithMany("PatientCards")
                        .HasForeignKey("ClerkId");

                    b.HasOne("MedicalClinic.Models.PatientModel", "Patient")
                        .WithOne("PatientCard")
                        .HasForeignKey("MedicalClinic.Models.PatientCardModel", "PatientId");
                });

            modelBuilder.Entity("MedicalClinic.Models.PatientModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Patient")
                        .HasForeignKey("MedicalClinic.Models.PatientModel", "UserId");
                });

            modelBuilder.Entity("MedicalClinic.Models.ReferralModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.AppointmentModel", "Appointment")
                        .WithMany("ReferralModel")
                        .HasForeignKey("AppointmentId");

                    b.HasOne("MedicalClinic.Models.ExaminationModel", "ExaminationModel")
                        .WithOne("ReferralModel")
                        .HasForeignKey("MedicalClinic.Models.ReferralModel", "ExaminationId");
                });

            modelBuilder.Entity("MedicalClinic.Models.WorkHoursModel", b =>
                {
                    b.HasOne("MedicalClinic.Models.DoctorModel", "DoctorModel")
                        .WithMany("WorkHours")
                        .HasForeignKey("DoctorId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MedicalClinic.Models.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MedicalClinic.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MedicalClinic.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("MedicalClinic.Models.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MedicalClinic.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MedicalClinic.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
